import React from "react";
import { motion } from "framer-motion";
import { Activity, Aperture, ShieldCheck, ScanFace } from "lucide-react";

export default function Architecture() {
  const cards = [
    {
      title: "Pixel-Level Saliency",
      icon: Aperture,
      description:
        "Our Vision Transformer (ViT) breaks the image into patches, scanning for microscopic compression artifacts and blending anomalies invisible to the human eye.",
    },
    {
      title: "Frequency Domain Analysis",
      icon: Activity,
      description:
        "Generative models leave specific signatures in the frequency domain. We use Discrete Cosine Transforms (DCT) to spot structural irregularities generated by AI.",
    },
    {
      title: "Biometric Liveness",
      icon: ScanFace,
      description:
        "For portraits, we extract remote photoplethysmography (rPPG) signals to detect genuine blood flow and micro-expressions that deepfakes fail to simulate.",
    },
    {
      title: "Ensemble Validation",
      icon: ShieldCheck,
      description:
        "The multi-modal signals are fused and cross-verified through a low-latency JAX/Flax inference engine, yielding a definitive confidence score in under 200ms.",
    },
  ];

  return (
    <section
      id="how-it-works"
      className="relative overflow-hidden bg-[#030910] scroll-mt-24 py-24"
    >
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(37,136,233,0.22),rgba(3,9,16,0)_45%)]" />

      <div className="relative mx-auto max-w-[1440px] px-6 lg:px-10 w-full">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="space-y-14"
        >
          <div className="text-center max-w-4xl mx-auto space-y-5">
            <h2 className="font-display text-5xl md:text-6xl font-semibold text-white leading-tight">
              How we detect the undetectable.
            </h2>
            <p className="text-xl text-white/65">
              A state-of-the-art hybrid architecture designed to catch the subtle synthetic cues
              that modern deepfake models leave behind.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {cards.map((card, index) => {
              const Icon = card.icon;
              return (
                <motion.div
                  key={card.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.08 }}
                  viewport={{ once: true }}
                  className="rounded-2xl border border-white/10 bg-[linear-gradient(180deg,rgba(10,23,38,0.7)_0%,rgba(7,15,25,0.85)_100%)] p-7 md:p-8 shadow-[inset_0_1px_0_rgba(130,190,255,0.12)]"
                >
                  <div className="h-10 w-10 rounded-lg border border-[#67c8ff]/25 bg-[#0f2740]/60 flex items-center justify-center mb-8">
                    <Icon className="h-5 w-5 text-[#84d2ff]" />
                  </div>
                  <h3 className="text-3xl font-display font-semibold text-white mb-4">{card.title}</h3>
                  <p className="text-white/62 leading-relaxed">{card.description}</p>
                </motion.div>
              );
            })}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
